### PR TITLE
Revamp the Protocol hierarchy

### PR DESCRIPTION
**Pull request by pitiphong-p**

### CODE REVIEW

**Review by nuxzero — APPROVED** [review]
All of them look good to me. 👏👏👏

I have a few questions. What is the purpose of `DataID`? Could you give me some of sample case that need to use `DataID`?

**Comment by pitiphong-p** [comment]
@nuxzero The main reason for `DataID` is to have a more restrict API on ID. DataID will help us validate the id string data if it's the correct ID of the specified type or not.

**Comment by nuxzero** [comment]
I see. 👍

**Review by igroomgrim — APPROVED** [review]
👍

**Pull request merged**
