### PR TITLE
[WIP] Set deployment target to support iOS 8.0

### PR DESCRIPTION
**Pull request by PH9**

### CODE REVIEW

**Comment by pitiphong-p** [comment]
What is the purpose for this change?

**Comment by PH9** [comment]
Back to support iOS 8.0 and above.
Not just 10.0 and above.

I believe many client have to support iOS 8 or 9

**Comment by pitiphong-p** [comment]
Well, please be noted that, this library is not intended to use on an iOS client. So we don't need to support iOS 8 or 9.

**Comment by PH9** [comment]
Thanks for information

**Pull request closed without merging**
